#!/bin/bash

# Get the root directory of the git repository
ROOT_DIR=$(git rev-parse --show-toplevel)

# Run the formatter script
bash "$ROOT_DIR/scripts/formatter.sh"

# Get the list of changed files and only add those that exist
changed_files=$(git diff --name-only --cached)
for file in $changed_files; do
    if [ -f "$file" ]; then
        git add "$file"
    fi
done 